name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  

    - name: Install dependencies
      run: yarn install

    - name: Build project
      run: yarn run build

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: ./.nuxt

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download build files
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: ./.nuxt

    - name: Deploy to server
      run: |
        yarn generate
      env:
        NUXT_APP_BASE_URL: ${{ vars.NUXT_APP_BASE_URL  }}